name: Checked Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  check:
    uses: windchime-yk/deno-util/.github/workflows/reuse_check.yml@publish-jsr
